[workspace]
resolver = "2"

members = [
    "nexus-common",
    "nexus-server",
    "nexus-client",
]

[workspace.package]
version = "0.5.16"
edition = "2024"

[profile.release]
strip = true
lto = "thin"
