# Icon font definition for Nexus client
module = "icon"

[glyphs]
bookmark = "fontawesome-bookmark"
chat = "fontawesome-chat"
close = "fontawesome-cancel"
cog = "fontawesome-cog"
collapse_left = "fontawesome-collapse-left"
edit = "fontawesome-pencil"
expand_right = "fontawesome-expand-right"
eye = "fontawesome-eye"
eye_off = "fontawesome-eye-off"
file = "fontawesome-doc"
file_archive = "fontawesome-file-archive"
file_audio = "fontawesome-file-audio"
file_code = "fontawesome-file-code"
file_excel = "fontawesome-file-excel"
file_image = "fontawesome-file-image"
file_pdf = "fontawesome-file-pdf"
file_powerpoint = "fontawesome-file-powerpoint"
file_text = "fontawesome-doc-text"
file_video = "fontawesome-file-video"
file_word = "fontawesome-file-word"
folder = "fontawesome-folder"
folder_empty = "fontawesome-folder-empty"
folder_root = "fontawesome-sitemap"
home = "fontawesome-home"
info = "fontawesome-info"
info_circled = "fontawesome-info-circled"
kick = "fontawesome-logout"
logout = "fontawesome-logout"
megaphone = "fontawesome-megaphone"
message = "fontawesome-chat"

newspaper = "fontawesome-newspaper"
plus = "fontawesome-plus"
refresh = "fontawesome-arrows-cw"
server = "fontawesome-server"
paste = "fontawesome-paste"
trash = "fontawesome-trash-empty"
down_dir = "fontawesome-down-dir"
up_dir = "fontawesome-up-dir"
user_plus = "fontawesome-user-plus"
users = "fontawesome-users"
exchange = "fontawesome-exchange"
download = "fontawesome-download"
upload = "fontawesome-upload"
pause = "fontawesome-pause"
play = "fontawesome-play"