# Icon font definition for Nexus client
module = "icon"

[glyphs]
bookmark = "fontawesome-bookmark"
chat = "fontawesome-chat"
close = "fontawesome-cancel"
cog = "fontawesome-cog"
collapse_left = "fontawesome-collapse-left"
edit = "fontawesome-pencil"
expand_right = "fontawesome-expand-right"
info = "fontawesome-info"
info_circled = "fontawesome-info-circled"
kick = "fontawesome-logout"
newspaper = "fontawesome-newspaper"
plus = "fontawesome-plus"
server = "fontawesome-server"
logout = "fontawesome-logout"
megaphone = "fontawesome-megaphone"
message = "fontawesome-chat"
trash = "fontawesome-trash-empty"
user_plus = "fontawesome-user-plus"
users = "fontawesome-users"